In [61]:
import cv2 as cv
import numpy as np

# image = np.zeros((400,400,3), dtype="uint8")
image = cv.imread('nested.png')
raw = image.copy()

# replace blue as white
# image[np.where((image==[255,255,0]).all(axis=2))] = [255,255,255]

# get contours
gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
edges = cv.Canny(gray, 100, 200)
cnts, hr = cv.findContours(edges, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

print(len(cnts))
print(hr)

for cnt in cnts:
    epsilon = 0.01*cv.arcLength(cnt, True)
    print(cv.approxPolyDP(cnt, epsilon, True))

cv.drawContours(image, cnts, -1, (0,0,0), 2)


cv.imshow('Test', image)
cv.imshow('Test2', edges)
cv.waitKey(0)
cv.destroyAllWindows()

4
[[[-1 -1  1 -1]
  [-1 -1  2  0]
  [-1 -1  3  1]
  [-1 -1 -1  2]]]
[[[ 47  24]]

 [[ 24  78]]

 [[ 46 135]]

 [[144 135]]

 [[167  80]]

 [[144  24]]]
[[[ 47  24]]

 [[144  25]]

 [[167  80]]

 [[142 136]]

 [[ 46 134]]

 [[ 24  78]]]
[[[ 72  66]]

 [[ 72  94]]

 [[118  94]]

 [[118  65]]]
[[[ 72  67]]

 [[ 74  65]]

 [[117  65]]

 [[118  93]]

 [[ 73  94]]]


In [62]:
import cv2
import numpy as np 
import matplotlib.pyplot as plt 

def callback(x):
    print(x)

img = cv2.imread('nested.png', 0) #read image as grayscale


canny = cv2.Canny(img, 85, 255) 

cv2.namedWindow('image') # make a window with name 'image'
cv2.createTrackbar('L', 'image', 0, 255, callback) #lower threshold trackbar for window 'image
cv2.createTrackbar('U', 'image', 0, 255, callback) #upper threshold trackbar for window 'image

while(1):
    numpy_horizontal_concat = np.concatenate((img, canny), axis=1) # to display image side by side
    cv2.imshow('image', numpy_horizontal_concat)
    k = cv2.waitKey(1) & 0xFF
    if k == 27: #escape key
        break
    l = cv2.getTrackbarPos('L', 'image')
    u = cv2.getTrackbarPos('U', 'image')

    canny = cv2.Canny(img, l, u)

cv2.destroyAllWindows()

1
2
5
6
7
8
9
10
11
14
15
16
17
18
19
20
23
24
25
26
27
29
31
34
35
36
37
39
42
44
46
48
51
52
53
57
58
60
61
62
63
65
66
67
68
70
73
75
76
77
79
80
82
84
85
86
90
91
92
94
99
103
109
110
111
112
113
114
117
118
119
121
122
126
127
130
131
133
135
137
138
139
142
143
145
147
148
150
151
152
154
155
156
159
160
161
163
164
165
164
161
160
159
158
156
155
153
152
151
150
148
142
133
127
114
107
91
85
73
59
53
49
48
45
44
42
41
33
26
24
22
20
16
11
8
2
0
5
9
15
20
26
31
37
41
44
53
60
63
68
75
85
96
104
113
119
125
127
130
133
135
137
141
143
144
146
147
151
152
154
155
160
161
160
156
154
147
143
134
120
110
102
92
88
78
68
65
53
50
45
43
41
36
32
31
26
25
23
15
6
3
2
5
14
19
28
37
41
49
52
60
62
70
75
82
90
93
99
103
108
112
117
119
122
124
125
126
128
130
131
133
134
135
137
138
141
142
143
147
151
152
153
155
156
159
160
159
158
156
155
156
158
159
158
156
155
1
2
3
6
7
8
9
10
12
17
18
19
20
22
23
26
27
29
31
32
34
35
36
37
40
41
44
45
46
48
50
52
53
56
57
58
59
60
62
63
65
67
68
73
7