In [25]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
print(x_train.shape)
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  # 图像矩阵拉成一个特征向量 
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

(60000, 28, 28)
Epoch 1/5
1875/1875 [==============================] - 2s 830us/step - loss: 0.2942 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 2s 861us/step - loss: 0.1462 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 2s 833us/step - loss: 0.1096 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 2s 817us/step - loss: 0.0869 - accuracy: 0.9726
Epoch 5/5
313/313 [==============================] - 0s 584us/step - loss: 0.0709 - accuracy: 0.9781


[0.0709087923169136, 0.9781000018119812]

In [22]:
import tensorflow as tf
from tensorflow.keras import layers

model = tf.keras.Sequential()
# 图像矩阵拉成一个特征向量 
model.add(layers.Flatten(input_shape=(28, 28)))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [23]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
            loss=tf.keras.losses.SparseCategoricalCrossentropy(),
            metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

In [24]:
model.fit(x_train, y_train, epochs=5, batch_size=64, 
         validation_data=(x_test, y_test))

Epoch 1/5
938/938 [==============================] - 1s 935us/step - loss: 0.3930 - sparse_categorical_accuracy: 0.8902 - val_loss: 0.2072 - val_sparse_categorical_accuracy: 0.9396
Epoch 2/5
938/938 [==============================] - 1s 821us/step - loss: 0.1907 - sparse_categorical_accuracy: 0.9449 - val_loss: 0.1748 - val_sparse_categorical_accuracy: 0.9465
Epoch 3/5
938/938 [==============================] - 1s 696us/step - loss: 0.1533 - sparse_categorical_accuracy: 0.9550 - val_loss: 0.1413 - val_sparse_categorical_accuracy: 0.9567
Epoch 4/5
938/938 [==============================] - 1s 717us/step - loss: 0.1310 - sparse_categorical_accuracy: 0.9617 - val_loss: 0.1331 - val_sparse_categorical_accuracy: 0.9606
Epoch 5/5
938/938 [==============================] - 1s 705us/step - loss: 0.1135 - sparse_categorical_accuracy: 0.9660 - val_loss: 0.1313 - val_sparse_categorical_accuracy: 0.9602


In [26]:
import numpy as np
input_data = np.arange(16)
input_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
# 转tensor
dataset = tf.data.Dataset.from_tensor_slices(input_data)
for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


In [31]:
# repeat batch
dataset = tf.data.Dataset.from_tensor_slices(input_data)
dataset = dataset.repeat(2).batch(4)
for data in dataset:
    print(data)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)
tf.Tensor([12 13 14 15], shape=(4,), dtype=int32)


In [32]:
# shuffle 洗牌
dataset = tf.data.Dataset.from_tensor_slices(input_data).shuffle(buffer_size=10).batch(4)
for data in dataset:
    print(data)

tf.Tensor([ 4  5  3 10], shape=(4,), dtype=int32)
tf.Tensor([ 1 13 12  6], shape=(4,), dtype=int32)
tf.Tensor([14  9 15 11], shape=(4,), dtype=int32)
tf.Tensor([7 2 0 8], shape=(4,), dtype=int32)


In [34]:
# 重新训练
train = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train = train.batch(32)
train = train.repeat()

valid = tf.data.Dataset.from_tensor_slices((x_test, y_test))
valid = valid.batch(32)
valid = valid.repeat()

model.fit(train, epochs=5, steps_per_epoch=100, validation_data=valid, validation_steps=100)

Epoch 1/5
100/100 [==============================] - 0s 3ms/step - loss: 0.0416 - accuracy: 0.9891 - val_loss: 0.1008 - val_accuracy: 0.9691
Epoch 2/5
100/100 [==============================] - 0s 3ms/step - loss: 0.0573 - accuracy: 0.9816 - val_loss: 0.1068 - val_accuracy: 0.9663
Epoch 3/5
100/100 [==============================] - 0s 2ms/step - loss: 0.0701 - accuracy: 0.9781 - val_loss: 0.1083 - val_accuracy: 0.9666
Epoch 4/5
100/100 [==============================] - 0s 3ms/step - loss: 0.0563 - accuracy: 0.9859 - val_loss: 0.1079 - val_accuracy: 0.9688
Epoch 5/5
100/100 [==============================] - 0s 3ms/step - loss: 0.0527 - accuracy: 0.9834 - val_loss: 0.1004 - val_accuracy: 0.9688


In [35]:
# fashion_mnist
# https://tensorflow.google.cn/tutorials/keras/classification

from tensorflow import keras
fashion_mnist = keras.datasets.fashion_mnist
(train_images, tanin_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 1s 0us/step


In [36]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']